# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="miloshadzic"
#ZSH_THEME="jispwoso"

DISABLE_AUTO_TITLE="true"

export UPDATE_ZSH_DAYS=7

export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"

plugins=(cabal git git-extras macports pip python npm osx sudo)

source $ZSH/oh-my-zsh.sh


if [ -d $HOME/.zshrc.d ]; then
  for file in $HOME/.zshrc.d/*.zsh; do
    source $file
  done
fi

